In [1]:
import json
import pandas as pd 

with open('/home/vlad/datasets/drons_vs_berds/coco/dataset/drons_vs_berds_test.json') as json_data:
    test_json = json.load(json_data)
with open('/home/vlad/datasets/drons_vs_berds/coco/dataset/drons_vs_berds_valid.json') as json_data:
    valid_json = json.load(json_data)
with open('/home/vlad/datasets/drons_vs_berds/coco/dataset/drons_vs_berds_train.json') as json_data:
    train_json = json.load(json_data)
 

/tmp/ipykernel_25616/1617324509.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [4]:
annotations = pd.DataFrame(train_json['annotations'])
annotations['area'].describe()

count     48136.000000
mean       1525.754674
std        6930.153119
min          16.000000
25%         168.000000
50%         364.000000
75%        1120.000000
max      211575.000000
Name: area, dtype: float64

In [7]:
annotations['w'] = annotations['bbox'].apply(lambda bbox : bbox[2])
annotations['h'] = annotations['bbox'].apply(lambda bbox : bbox[3])

In [28]:
annotations['w'].max()

525

In [29]:
annotations['h'].max()

403

In [16]:
annotations[['w','h']].to_numpy()

array([[ 70,  27],
       [ 70,  27],
       [ 70,  27],
       ...,
       [103,  50],
       [108,  53],
       [108,  53]])

In [17]:
from sklearn.cluster import KMeans
import numpy as np
 
kmeans = KMeans(n_clusters=5, random_state=0, n_init="auto").fit(annotations[['w','h']].to_numpy())
kmeans.labels_
 

array([0, 0, 0, ..., 4, 4, 4], dtype=int32)

In [ ]:
MODEL.ANCHOR_GENERATOR.SIZES = [[32], [64], [128], [256], [512]]
MODEL.ANCHOR_GENERATOR.ASPECT_RATIOS = [[0.5, 1.0, 2.0]]

In [25]:
kmeans.cluster_centers_

array([[ 42.00379478,  29.95150273],
       [ 17.28690089,  12.84013799],
       [170.20020222,  93.61577351],
       [463.01052632, 296.18947368],
       [ 88.55038567,  56.15327196]])

In [27]:
(kmeans.cluster_centers_[:,1] * kmeans.cluster_centers_[:,0])**0.5

array([ 35.46937798,  14.89852989, 126.22766568, 370.32262164,
        70.51520324])

In [21]:
kmeans.cluster_centers_[:,1] / kmeans.cluster_centers_[:,0]

array([0.71306659, 0.74276691, 0.55003327, 0.63970354, 0.63413921])

In [19]:
annotations = pd.DataFrame(valid_json['annotations'])
annotations['area'].describe()

count     7068.000000
mean      1407.778862
std       5043.151991
min         15.000000
25%        200.000000
50%        600.000000
75%       1201.000000
max      84987.000000
Name: area, dtype: float64

In [20]:
annotations = pd.DataFrame(train_json['annotations'])
annotations['area'].describe()

count     48136.000000
mean       1525.754674
std        6930.153119
min          16.000000
25%         168.000000
50%         364.000000
75%        1120.000000
max      211575.000000
Name: area, dtype: float64

In [15]:
annotations = pd.DataFrame(test_json['annotations'])
annotations['area'].describe()

count     3729.000000
mean      1609.391258
std       3505.232912
min         63.000000
25%        169.000000
50%        320.000000
75%        868.000000
max      19932.000000
Name: area, dtype: float64